name: Create Q1_archive_README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Archive folder
      run: |
        mkdir -p Archive  # Crée le dossier Archive si il n'existe pas

    - name: Copy README.md to Archive folder
      run: |
        cp README.md Archive/Q1_archive_README.md  # Copie README.md dans le dossier Archive

    - name: Configure Git
      run: |
        git config --global user.name "Drmama343"
        git config --global user.email "poretmathys2004@gmail.com"

    - name: Commit and push changes
      run: |
        git add Archive/Q1_archive_README.md  # Ajoute le fichier dans Archive
        git commit -m "Add Q1_archive_README.md with README.md content"
        git push
