name: Create Q1_archive_README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-and-commit:
    runs-on: ubuntu-latest

    steps:
    # Vérifiez le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Copiez le contenu de README.md dans Q1_archive_README.md
    - name: Copy README.md
      run: |
        cp README.md Q1_archive_README.md

    # Configurez Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Ajoutez, commettez et poussez le fichier
    - name: Commit and push changes
      run: |
        git add Q1_archive_README.md
        git commit -m "Add Q1_archive_README.md with README.md content"
        git push
