name: Create Q2_archive_README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Q2_archive_README.md in Archive folder
      run: |
        mkdir -p Archive  # Créer le dossier Archive si ce n'est pas déjà fait
        echo "Nom : PORET" > Archive/Q2_archive_README.md
        echo "Prénom : Mathys" >> Archive/Q2_archive_README.md
        echo "Date et heure d'exécution : $(date '+%Y-%m-%d %H:%M:%S')" >> Archive/Q2_archive_README.md
        echo "" >> Archive/Q2_archive_README.md
        echo "Contenu de README.md :" >> Archive/Q2_archive_README.md
        echo "-----------------------" >> Archive/Q2_archive_README.md
        cat README.md >> Archive/Q2_archive_README.md

    - name: Configure Git
      run: |
        git config --global user.name "Drmama343"
        git config --global user.email "poretmathys2004@gmail.com"

    - name: Commit and push changes
      run: |
        git add Archive/Q2_archive_README.md
        git commit -m "Add Q2_archive_README.md with README.md content"
        git push