name: Create Q4_archive_date.txt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Créer le fichier Q4_archive_date.txt dans Archive
    - name: Create Q4_archive_date.txt in Archive folder
      run: |
        mkdir -p Archive  # Créer le dossier Archive si ce n'est pas déjà fait
        echo "Nom : PORET" > Archive/Q4_archive_date.txt
        echo "Prénom : Mathys" >> Archive/Q4_archive_date.txt
        echo "Date et heure d'exécution : $(date '+%Y-%m-%d %H:%M:%S')" >> Archive/Q4_archive_date.txt
        echo "" >> Archive/Q4_archive_date.txt
        echo "Contenu du fichier Q4.java :" >> Archive/Q4_archive_date.txt
        echo "------------------------" >> Archive/Q4_archive_date.txt
        cat Java/Q4.java >> Archive/Q4_archive_date.txt

    # Étape 3 : Configurer Git
    - name: Configure Git
      run: |
        git config --global user.name "Drmama343"
        git config --global user.email "poretmathys2004@gmail.com"

    # Étape 4 : Commit et push
    - name: Commit and push changes
      run: |
        git add Archive/Q4_archive_date.txt
        git commit -m "Add Q4_archive_date.txt with Q4.java content"
        git push
